//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_NTUT                        132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_back                        161
#define IDB_playerA                     162
#define IDB_BITMAP3                     164
#define IDB_BITMAP4                     165
#define IDB_picTest                     165
#define IDB_mapA                        166
#define IDB_mapB                        167
#define IDB_playerA_2                   169
#define IDB_playerB_2                   171
#define IDB_BITMAP6                     172
#define IDB_playerB                     172
#define IDB_BITMAP5                     173
#define IDB_AttackBR                    182
#define IDB_Bweapon                     183
#define IDB_AttackBL                    185
#define IDB_BITMAP7                     190
#define IDB_AttackAL                    191
#define IDB_AttackAR                    192
#define IDB_bar                         193
#define IDB_blood                       194
#define IDB_mana                        195
#define IDB_jumpA_L                     196
#define IDB_jumpA_R                     197
#define IDB_jumpB_L                     198
#define IDB_jumpB_R                     199
#define IDB_defendA_L                   200
#define IDB_defendA_R                   201
#define IDB_defendB_L                   202
#define IDB_defendB_R                   203
#define IDB_test_weapon                 204
#define IDB_start_button                205
#define IDB_BITMAP8                     206
#define IDB_runA_L                      207
#define IDB_runA_R                      208
#define IDB_runB_L                      209
#define IDB_runB_R                      210
#define IDB_runA_L_2                    211
#define IDB_runA_R_2                    212
#define IDB_runB_L_2                    213
#define IDB_runB_R_2                    214
#define IDB_BITMAP9                     215
#define IDB_playerA_logo                215
#define IDB_playerB_logo                216
#define IDB_AweaponBall_L               217
#define IDB_AweaponBall_R               218
#define IDB_Aweapon_Continue_L          219
#define IDB_Aweapon_Continue_R          220
#define IDB_A_breath_L                  221
#define IDB_A_breath_R                  222
#define IDB_B_breath_L                  223
#define IDB_B_breath_R                  224
#define IDB_A_walk_L                    225
#define IDB_A_walk_R                    226
#define IDB_B_walk_L                    227
#define IDB_B_walk_R                    228
#define IDB_AttackA_L_2                 229
#define IDB_AttackA_R_2                 230
#define IDB_Askill1_L                   231
#define IDB_Askill1_R                   232
#define IDB_Askill2_L                   233
#define IDB_Askill2_R                   234
#define IDB_Askill3                     235
#define IDB_B_DLJ1                      236
#define IDB_B_DLJ2                      237
#define IDB_B_DRJ1                      238
#define IDB_B_DRJ2                      239
#define IDB_toolKind_1                  240
#define IDB_toolKind_2                  241
#define IDB_toolKind_3                  242
#define IDB_toolKind_4                  243
#define IDB_toolKind_5                  244
#define IDB_toolKind_6                  245
#define IDB_toolKind_7                  246
#define IDB_toolKind_8                  247
#define IDB_END_A1                      248
#define IDB_END_A2                      249
#define IDB_END_B1                      250
#define IDB_END_B2                      251
#define IDB_BITMAP10                    252
#define IDB_introduce                   252
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775
#define ID_BUTTON32776                  32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        253
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
